#using a simple lightweight python
FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py ./
COPY predictions.py ./

#getting the model from EC2 instance
COPY model/BrainTumorPrediction.h /app/model

EXPOSE 8000

CMD["uvicorn","main:app","--host","0.0.0.0","--port","8000","workers","1"]
